### ISSUE TITLE
make-listener的bug/A bug in make-listener commands

### ISSUE THREAD

**Issue by lijialong1313** [zencodex/package-make#1]
当我使用

`php artisan package:make-listener TestListener TestPackage --event=TestEvent`

时

他会报错误，错误是：
`Argument 1 passed to Laravel\Package\Commands\ListenerMakeCommand::getEventName() must be an instance of Laravel\Package\Module`

我看了以下代码，只需要改：
`protected function getEventName(Module $module)`
改为：
`protected function getEventName(\Laravel\Package\Manager $module)`

即可解决。
————————————————————————————————————————————————————————
When I use
`php artisan package:make-listener TestListener TestPackage --event=TestEvent`

It give me an error message like:
`Argument 1 passed to Laravel\Package\Commands\ListenerMakeCommand::getEventName() must be an instance of Laravel\Package\Module`

I read about the code then I find a way to fix it ,just change 
`protected function getEventName(Module $module)`
to
`protected function getEventName(\Laravel\Package\Manager $module)`

and this bug will be fixed.

**Comment by zencodex** [comment]
many thanks, fixed in v1.0.4
